name: DAST Scan - OWASP ZAP

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  dast:
    name: OWASP ZAP DAST Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Start Juice Shop server
        run: |
          npm start &
          sleep 15   # wait for server to start
        env:
          PORT: 3000

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: 'http://localhost:3000'
          format: 'html'
          output: 'zap_report.html'
          fail_on_risk: 'High'
          cmd_options: '-t http://localhost:3000 -r zap_report.html'

      - name: Upload DAST Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html
