name: DAST Scan - OWASP ZAP

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  dast:
    name: OWASP ZAP DAST Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Start Juice Shop server
        run: |
          npm start &
          sleep 15   # wait for server to start
        env:
          PORT: 3000

      - name: Make workspace writable for ZAP
        run: chmod -R a+rw ./juice-shop

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: 'http://localhost:3000'
          cmd_options: '-t http://localhost:3000 -r zap_report.html -J zap_report.json -w zap_report.md'
          fail_action: 'warn'       # optional: fails workflow on high risk if needed
          artifact_name: 'zap-report'

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-html
          path: zap_report.html

      - name: Upload JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-json
          path: zap_report.json

      - name: Upload Markdown Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-md
          path: zap_report.md
